### ISSUE TITLE
Wiki I/O configuration

### ISSUE THREAD

**Issue by Upcycle-Electronics** [ghidraninja/game-and-watch-hacking#1]
Hey,
 Why does the wiki [here](https://github.com/ghidraninja/game-and-watch-hacking/wiki/GPIOs) list:

> GPIOB
...
Pin 6
	Mode: Alternate function mode
	AF: 4 (I2C1_SCL)
Pin 7
	Mode: Alternate function mode
	AF: 4 (I2C1_SDA)

... when these pins are not connected to anything?

**Comment by nezza** [comment]
That's directly parsed from the GPIO peripheral configuration - might be by mistake, but that's the state the IO is in in stock firmware :)

**Comment by Upcycle-Electronics** [comment]
Interesting. I wonder what would happen if the pull down resistors that are used to disable the DA9230's I2C connection were removed and bodge wires connected. Thanks for the info.
