### ISSUE TITLE
NAU8315 Package Type

### ISSUE THREAD

**Issue by honeycuttGitHub** [ghidraninja/game-and-watch-hacking#2]
The audio IC package type is not listed. This information may be available elsewhere but I think it would be useful to have it listed on the datasheets page as the 12-pin package, NAU8315B31VG. Photo attached is of the 
board after I removed my damaged audio IC to check. 
![20210722_222223](https://user-images.githubusercontent.com/41033875/126731293-488af3aa-b4b1-4336-9ada-c7e9ad0836b2.jpg)

**Comment by DNA64** [comment]
Hi,
You can find this information and everything else very well detailed already here:
https://github.com/Upcycle-Electronics/game-and-watch-hardware

This link and more are available in the wiki on r/GameAndWatchMods
